### ISSUE TITLE
How to use the SceneTextOCR

### ISSUE THREAD

**Issue by robbiewongBD** [BenjaminTrapani/SceneTextOCR#11]
I note the repo is CNTK written，so how shoud I use this SceneTextOCR with my installed CNTK

**Comment by BenjaminTrapani** [comment]
Hi Robbie, apologies for the delay. I'm working on some instructions for building. The project uses the C++ API, which requires a few other development libraries to be installed. I'll provide a docker container with the dependencies set up and will get the webpage working again (noip canceled my domain name).

**Comment by BenjaminTrapani** [comment]
Webpage is still pending on the new domain propagating through, but I've updated the readme and pushed some docker containers that should let you begin using the model. I'll work on supporting a linux build for the map file generator as well, which provides the input to the training binary in the format expected by CNTK.

**Comment by BenjaminTrapani** [comment]
The website with a demo of the model is up again at https://gpuandai.com/#/. Please let me know if you need any help getting up and running or run into issues setting things up. Closing this issue for now.
